### ISSUE TITLE
I need to contact the dev team of the nExt Camera app

### ISSUE THREAD

**Issue by satyr-bravo** [nExtCamera/libuac#1]
I am a cinema student, and I use the nExt Camera app to monitor my camera because I can't afford a proper monitor.

I know that asking you to do more work is a bit arrogant, but I desperately need a frame guide feature. Is it possible for you to add it?

If not, could you maybe share the access to the app's code so I can try to add it myself?  I can sign an NDA if needed. 

If you'd like contact me in a more convenient way than github issues, here's my email:

miron1733 @ gmail dot com (sorry, i'm trying to avoid getting this email scraped)

Sorry for littering your issues, but i didn't find a better way to contact you. 
Thank you!

**Comment by jksiezni** [comment]
Hello, you can use a contact email from official App page (https://play.google.com/store/apps/details?id=pl.nextcamera), or get it from the About screen in the App settings. Cheers.
